// main.c - Project Euler (problem2): Even Fibonacci Numbers

// Each new term in the Fibonacci sequence is generated by adding the previous two terms.
// By starting with and , the first terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million,
// find the sum of the even-valued terms.

#include <stdio.h>
#include "timer.h"

int get_fib_recurs(int cnt);

int main(void)
{
    	int fib = 1;
	int cnt = 1;                           
    	int answ = 0;

    	TIMER_START
  
	while(fib < 4000000)
	{
		
		fib = get_fib_recurs(cnt);
		if(fib % 2 == 0)
			answ += fib;
		//printf("%d - %d \n", cnt, fib);
		cnt++;
	}
	
	TIMER_STOP
    	TIMER_PRINT

    	printf("answer  = %d\n", answ);   // выводим результат

    	return 0;
}

int get_fib_recurs(int cnt)
{
	if(cnt <= 1)
		return 1;
	else
		return get_fib_recurs(cnt - 1) + get_fib_recurs(cnt - 2);
}

