// main_array.c - Project Euler (problem2): Even Fibonacci Numbers
// solution by array

// Each new term in the Fibonacci sequence is generated by adding the previous two terms.
// By starting with and , the first terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million,
// find the sum of the even-valued terms.

#include <stdio.h>
#include "timer.h"
#include "header.h"
#include "funcs.c"

int main(void)
{
	int fib_num = 1;                           
   	int answ = 0;
	int arr[] = {1, 1};

   	TIMER_START
  
	while(fib_num < 4000000)
	{	
		fib_num = get_next_fib(arr);
		if(fib_num % 2 == 0)
			answ += fib_num;
	}
	
	TIMER_STOP

	printf("Solution by array\n");
   	TIMER_PRINT
   	printf("answer  = %d\n", answ);

   	return 0;
}


