// main.c - Project Euler (problem2): Even Fibonacci Numbers

// Each new term in the Fibonacci sequence is generated by adding the previous two terms.
// By starting with and , the first terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million,
// find the sum of the even-valued terms.

#include <stdio.h>
#include "timer.h"
#include "header.h"
#include "funcs.c"

int main(void)
{
    	int ser_num = 1;
	int fib_num = 1;                           
    	int answ = 0;

    	TIMER_START
  
	while(fib_num < 4000000)
	{
		fib_num = get_fib_recurs(ser_num);
		if(fib_num % 2 == 0)
			answ += fib_num;
		ser_num++;
	}
	
	TIMER_STOP

	printf("Solution by recusion\n");
    	TIMER_PRINT
    	printf("answer  = %d\n", answ);

    	return 0;
}


